services:
  podman:
    image: podman-stale-pause-pid-bug
    user: testuser
    security_opt:
      - seccomp=unconfined
      - label=disable
    devices:
      - /dev/fuse
    command: podman --log-level=debug run --rm docker.io/library/hello-world
