services:
  podman:
    image: podman-stale-pause-pid-bug
    build:
      context: .
      dockerfile: Dockerfile
    user: testuser
    security_opt:
      - seccomp=unconfined
      - label=disable
    devices:
      - /dev/fuse
    # command: podman --log-level=debug run --rm docker.io/library/hello-world
    command: podman --log-level=debug system info
